SELECT TO_CHAR(SALES_DATE,'YYYY') AS YEAR
     , TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS MONTH
     , GENDER
     , COUNT(DISTINCT B.USER_ID) AS USERS
  FROM USER_INFO A 
     , ONLINE_SALE B
 WHERE A.USER_ID = B.USER_ID
   AND GENDER IS NOT NULL
 GROUP BY TO_CHAR(SALES_DATE,'YYYY'), TO_NUMBER(TO_CHAR(SALES_DATE,'MM')), GENDER
 ORDER BY 1,2,3