SELECT TO_CHAR(SALES_DATE,'YYYY') AS YEAR
     , TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS MONTH
     , COUNT(DISTINCT I.USER_ID) AS PURCHASED_USERS 
     , ROUND(COUNT(DISTINCT I.USER_ID) / (SELECT COUNT(USER_ID) 
                                            FROM USER_INFO A
                                           WHERE TO_CHAR(A.JOINED,'YYYY') = '2021')
     ,1) AS PUCHASED_RATIO      
  FROM USER_INFO I
     , ONLINE_SALE S
 WHERE I.USER_ID(+) = S.USER_ID
   AND TO_CHAR(I.JOINED,'YYYY') = '2021'
 GROUP BY TO_CHAR(SALES_DATE,'YYYY'),TO_CHAR(SALES_DATE,'MM')
 ORDER BY TO_CHAR(SALES_DATE,'YYYY'),TO_CHAR(SALES_DATE,'MM')