SELECT '/home/grep/src/' || A.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT AS FILE_PATH
  FROM ( SELECT BOARD_ID
           FROM (SELECT BOARD_ID 
                   FROM USED_GOODS_BOARD
                  ORDER BY VIEWS DESC)
          WHERE ROWNUM <= 1
      ) A
     , USED_GOODS_FILE B
 WHERE A.BOARD_ID = B.BOARD_ID
 ORDER BY FILE_ID DESC