SELECT CAR_ID
     , C.CAR_TYPE
     , (DAILY_FEE*30) * (100-DISCOUNT_RATE) / 100 AS FEE
  FROM CAR_RENTAL_COMPANY_CAR C 
     , CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
 WHERE C.CAR_TYPE = P.CAR_TYPE 
   AND P.DURATION_TYPE = '30일 이상'
   AND CAR_ID NOT IN (SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE TO_CHAR(END_DATE, 'YYYYMMDD') > '20221101'
                     )
   AND C.CAR_TYPE IN ('세단', 'SUV')
   AND (DAILY_FEE*30) * (100-DISCOUNT_RATE) / 100 >= 500000
   AND (DAILY_FEE*30) * (100-DISCOUNT_RATE) / 100 < 2000000
 ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC