WITH TIME AS
(SELECT LEVEL - 1 AS HOUR
   FROM DUAL
CONNECT BY LEVEL <= 24),
ANIMAL AS
(SELECT TO_CHAR(DATETIME,'HH24') AS DATETIME
      , COUNT(*) AS CNT
  FROM ANIMAL_OUTS
 GROUP BY TO_CHAR(DATETIME,'HH24')
)
SELECT T.HOUR 
     , NVL(CNT,0) AS COUNT
  FROM TIME T
     , ANIMAL A
 WHERE T.HOUR = A.DATETIME(+)
 ORDER BY T.HOUR