SELECT USER_ID	
     , NICKNAME
     , CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2 AS 전체주소
     , SUBSTR(TLNO,0,3)||'-'||SUBSTR(TLNO,4,4)||'-'||SUBSTR(TLNO,8) AS 전화번호
  FROM USED_GOODS_USER A
     ,(SELECT WRITER_ID
          FROM USED_GOODS_BOARD 
         GROUP BY WRITER_ID
         HAVING COUNT(*) >= 3
       ) B
 WHERE A.USER_ID = B.WRITER_ID
 ORDER BY USER_ID DESC