SELECT FLAVOR
  FROM (SELECT ROW_NUMBER() OVER(ORDER BY SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) DESC) AS RNUM
             , B.FLAVOR
          FROM FIRST_HALF A
             , JULY B
         WHERE A.FLAVOR = B.FLAVOR(+)
         GROUP BY B.FLAVOR
        )
WHERE RNUM <=3