SELECT USER_ID
     , MAX(NICKNAME) AS NICKNAME
     , SUM(PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD A
     , USED_GOODS_USER B
 WHERE A.WRITER_ID = B.USER_ID
   AND A.STATUS = 'DONE'
 GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
 ORDER BY TOTAL_SALES