SELECT MEMBER_NAME
     , C.REVIEW_TEXT
     , TO_CHAR(C.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
  FROM MEMBER_PROFILE A
     , (SELECT ROW_NUMBER()OVER(ORDER BY COUNT(*) DESC) AS RNUM
             , MEMBER_ID
          FROM REST_REVIEW
         GROUP BY MEMBER_ID
        ) B
     , REST_REVIEW C
 WHERE B.RNUM = 1
   AND A.MEMBER_ID = B.MEMBER_ID
   AND B.MEMBER_ID = C.MEMBER_ID
 ORDER BY C.REVIEW_DATE, C.REVIEW_TEXT