SELECT *
  FROM (SELECT PRODUCT_CODE
              , SUM(SALES_AMOUNT) * MAX(PRICE) AS SALES
          FROM PRODUCT A
             ,  OFFLINE_SALE B
         WHERE A.PRODUCT_ID = B.PRODUCT_ID
         GROUP BY PRODUCT_CODE
      )
 ORDER BY SALES DESC, PRODUCT_CODE