SELECT B.PRODUCT_ID
     , MAX(A.PRODUCT_NAME) AS PRODUCT_NAME
     , SUM(A.PRICE*AMOUNT) AS TOTAL_SALES
  FROM FOOD_PRODUCT A
     , FOOD_ORDER B
 WHERE A.PRODUCT_ID = B.PRODUCT_ID
   AND TO_CHAR(B.PRODUCE_DATE,'YYYYMM') = '202205'
 GROUP BY B.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, B.PRODUCT_ID