SELECT A.APNT_NO	
     , P.PT_NAME
     , A.PT_NO
     , A.MCDP_CD
     , D.DR_NAME
     , A.APNT_YMD
  FROM APPOINTMENT A
     , PATIENT P
     , DOCTOR D
 WHERE A.PT_NO = P.PT_NO
   AND A.MDDR_ID = D.DR_ID
   AND TO_CHAR(APNT_YMD,'YYYYMMDD') = '20220413'
   AND A.MCDP_CD = 'CS'
   AND APNT_CNCL_YN = 'N'
 ORDER BY APNT_YMD