SELECT A.REST_ID
     , REST_NAME
     , FOOD_TYPE
     , FAVORITES
     , ADDRESS
     , SCORE
 FROM REST_INFO A
     ,(SELECT REST_ID
             , ROUND(AVG(REVIEW_SCORE),2) AS SCORE
         FROM REST_REVIEW
        GROUP BY REST_ID
       ) B
 WHERE A.REST_ID = B.REST_ID
   AND A.ADDRESS LIKE '서울%'
 ORDER BY SCORE DESC, FAVORITES DESC